version: '3.9'

services:
  db:
    container_name: url-shortening-db
    image: postgres:15-alpine
    volumes:
      - url_shortening_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - ./.env.dev

volumes:
  url_shortening_db: